version: "3"
services:

  activemq:
    image: "rabbitmq:3-management"
    ports:
    - ${mq_port}:5672
    - ${mq_admin_port}:15672

  umbra:
    build: umbra
    links:
    - activemq
    command: ["wait-for-it.sh activemq:5672 -- start.sh"]



    
