BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/x86_64/
Include: yum

%post
    yum install -y \
        git \
        wget \
        which

    #Python36
    #https://linuxize.com/post/how-to-install-python-3-on-centos-7/
    yum install -y centos-release-scl
    yum install -y rh-python36

    source /opt/rh/rh-python36/enable

    #Update pip, just good practice
    pip install -U pip

    #Chromium
    #https://www.hiroom2.com/2017/08/11/centos-7-chromium-en/
    yum install -y epel-release
    yum install -y chromium

    #
    # Install the python library publicsuffix directly from git because install from pip
    # fails in python3
    #
    # Fixed in commit, f774d0b31b2bace6076b2ff723933692f63b585e
    # 	return codecs.open(os.path.join(os.path.dirname(__file__), name), encoding='utf8').read()
    pip install git+https://www.tablix.org/~avian/git/publicsuffix.git

    #Install Umbra master branch, as the project do not do releases
    pip install git+https://github.com/internetarchive/umbra.git

    chmod 755 /usr/bin/run-chromium

%files
    #
    # This script (ruthlessly stolen from https://github.com/mark-adams/docker-chromium-xvfb) replaces the chrome and
    # chromium startup scripts and ensures that whichever you call, chromium is started in a headless Xvfb display
    #
    run-chromium /usr/bin/run-chromium

%startscript
    #Default values of environment, if not set with SINGULARITYENV_
    export ACTIVEMQ_USER=${ACTIVEMQ_USER-:guest}
    export ACTIVEMQ_PASS=${ACTIVEMQ_PASS-:guest}
    export ACTIVEMQ_SERVER=${ACTIVEMQ_SERVER-:activemq}
    export ACTIVEMQ_PORT=${ACTIVEMQ_PORT-:5672}

    echo "amqp://$ACTIVEMQ_USER:$ACTIVEMQ_PASS@$ACTIVEMQ_SERVER:$ACTIVEMQ_PORT/%2f" @>> $PWD/umbra.log

    source scl_source enable rh-python36 @>> $PWD/umbra.log

    ulimit -c 0
    drain-queue --url "amqp://$ACTIVEMQ_USER:$ACTIVEMQ_PASS@$ACTIVEMQ_SERVER:$ACTIVEMQ_PORT/%2f" @>> umbra.log
    umbra -n 5 --executable /usr/bin/run-chromium  --url "amqp://$ACTIVEMQ_USER:$ACTIVEMQ_PASS@$ACTIVEMQ_SERVER:$ACTIVEMQ_PORT/%2f" @>> $HOME/umbra.log
