#!/bin/bash

## From https://github.com/mark-adams/docker-chromium-xvfb/blob/master/images/base/xvfb-chromium

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

if ! xlsclients -display :99; then
  # Start Xvfb
  Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
  xvfb=$!
else
  echo "Display :99 already running."
fi

export DISPLAY=:99

echo Starting chromium

echo Running "chromium --no-sandbox $@ &"
chromium --no-sandbox  $@ &
chromium=$!

wait $chromium
wait $xvfb
